### PR TITLE
Small superbuild fixes

### PR DESCRIPTION
**Pull request by paulinus**

### CODE REVIEW

**Comment by edgarriba** [comment]
cool! thks!

**Comment by edgarriba** [comment]
@paulinus @dakotabenjamin take look into latest commits. I finally decided to rewrite the run.py in order to have a more clear api.

**Comment by dakotabenjamin** [comment]
wow I'm gonna have to take some time to look at all this! 

Quick question, will this build in 12.04?

**Comment by dakotabenjamin** [comment]
Also, you may want to consult with @GeospatialDaryl, he has been working on an object oriented approach to the run script

**Comment by edgarriba** [comment]
@dakotabenjamin haven't tried yet with 12.04. Regarding OO, I've taken @GeospatialDaryl  basic strucures and rewrited in a more standard Python style following this: https://google.github.io/styleguide/pyguide.html

**Pull request merged**
